const roles = {
  Sales: [
    "Sales Associate",
    "Sales Representative",
    "Sales Manager",
    "Sales Real Estate ",
    "Sales Person",
    "Sales Analyst",
    "Sales Engineer",
    "Inside Sales",
    "Business development",
  ],
  Marketing: [
    "Marketing Specialist",
    "Marketing Manager",
    "Marketing Director",
    "Marketing Research",
    "Marketing Consultant",
    "Product Manager",
    "Public Relations",
    "Social Media Manager",
    "Brand Manager ",
    "SEO Manager",
    "Content Marketing",
    "Copywriter",
    "Digital Marketing",
    "eCommerce Marketing ",
    "Community Manager",
    "Growth hacker",
    "Content writer",
    "Video editor",
  ],
  Data: [
    "Data analyst",
    "Data scientist",
    "Data engnieer",
    "Big data engineer",
    "Machine learning engineer",
    "Business analyst",
    "Product analyst",
    "Risk analyst",
    "Biostatistician",
    "Markerting analyst",
    "Data Scientist - NLP",
    "Data Scientist - Deep learning",
    "MLOps",
    "Tableau developer",
    "PowerBI developer",
  ],
  Developer: [
    "Web developer",
    "Android developer",
    "SQL Developer",
    "Software Engineer",
    "UI/UX Designer",
    "DevOps Engineer",
    "Cloud Architect",
    "Web3 developer",
    "iOS developer",
    "Technical Lead - IT",
    "Delivery Manager - IT",
    "AWS developer",
    "Azure developer",
    "GCP developer",
    "Flutter developer",
    "Python developer",
    "React developer",
    "Javascript developer",
    "Full-stack Java Developer",
    "Full-stack Node.js Developer",
    "Full-stack PHP Developer",
    "Full-stack Python Developer",
    "Engineering Manager",
    "Embedded engineer",
    "Block chain developer",
    "SDE I",
    "SDE II",
    "SDE III",
    "Full-stack Developer",
  ],
  ITAdministrator: [
    "Network Administrator",
    "Linux administrator",
    "Cyber security",
    "IT Support",
    "Database administrator",
  ],
  CustomerService: [
    "Virtual Assistant",
    "Customer Service",
    "Customer Support",
    "BPO",
    "Telemarketer",
    "Delivery Partner",
    "Tele Sales",
  ],
  Operations: [
    "Operations Manager",
    "Operations Assistant",
    "Operations Coordinator",
    "Operations Analyst",
    "Operations Director",
    "Scrum Master",
    "Project Manager - IT",
  ],
  Engineering: [
    "Mechanical Engineer",
    "Civil Engineer",
    "Electrical Engineer",
    "Chemical Engineer",
    "Engineering Technician",
    "Geological Engineer",
    "Biomedical engineer",
    "Maintenance Engineer",
    "Mining Engineer",
    "Nuclear Engineer",
    "Petroleum Engineer",
    "Plant Engineer",
    "Production Engineer",
    "Quality Engineer",
    "Safety Engineer",
    "Biomedical engineer",
    "CAD Engineer",
    "NDT Engineer",
    "Marine engineer",
  ],
  FinanceAndAccounting: [
    "Accountant",
    "Accounting Director",
    "Auditor",
    "Controller",
    "Financial Analyst",
    "Finance Manager",
    "Financial Representative",
  ],
  Adminstration: [
    "Receptionist",
    "Account Executive",
    "Branch Manager",
    "Human Resources",
    "Secretary",
    "Account Manager",
    "Program Manager",
    "Data Entry",
  ],
};

module.exports = roles;
