import { Inter } from "@next/font/google";
import Head from "next/head";
import Banner from "../components/Banner";
import FindJobs from "../components/FindJobs";
import JobsPage from "./JobsPage";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      {/* <script
        async
        src="https://tag.clearbitscripts.com/v1/pk_36365288dc41bf93a0f347b2806a88a3/tags.js"
        referrerPolicy="strict-origin-when-cross-origin"
      ></script> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Banner />
        <FindJobs />
        <JobsPage />
      </div>
    </>
  );
}
